name: syncfusion_flutter_pdfviewer
description: Flutter PDF Viewer library is used to display a PDF document seamlessly and efficiently.
version: 21.1.37
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer

environment:
  sdk: ^3.6.0
  flutter: ">=1.20.0"

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  plugin:
    platforms:
      android:
        package: com.syncfusion.flutter.pdfviewer
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      ios:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
      web:
        default_package: syncfusion_pdfviewer_web
      macos:
        default_package: syncfusion_pdfviewer_macos
      windows:
        default_package: syncfusion_pdfviewer_windows

dependencies:
  flutter:
    sdk: flutter
  vector_math:
  async:
  http:
  uuid:
  device_info_plus:
#  intl: ">=0.17.0 <0.20.0"

  syncfusion_pdfviewer_platform_interface:

  syncfusion_pdfviewer_web:

  syncfusion_pdfviewer_macos:
  
  syncfusion_pdfviewer_windows:

  syncfusion_flutter_core:

  syncfusion_flutter_pdf:

  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
